stages:
  - test
  - build
  - deploy

image: python:3.7

pages:
  image: python:3.6
  stage: build
  script:
  - pip install -r requirements.txt
  - pip install .
  - pip install -r requirements_dev.txt
  - make docs
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master


test-python-27:
  stage: test
  image: python:2.7
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - python setup.py install
    - coverage run setup.py test
    - coverage report -m
  
test-python-36:
  stage: test
  image: python:3.6
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - python setup.py install
    - coverage run setup.py test
    - coverage report -m

test-python-37:
  stage: test
  image: python:3.7
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - python setup.py install
    - coverage run setup.py test
    - coverage report -m
  allow_failure: true

wheel:
  image: python:3.6
  stage: build
  script:
    - pip install wheel
    # Build wheel
    - python setup.py sdist bdist_wheel --universal
  dependencies: []
  artifacts:
    expire_in: 3h
    paths:
      - dist

deploy:wheel:
  image: python:3.7
  stage: deploy
  script:
    - pip install twine
    - twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD dist/*
  only:
    # Only upload the repository on a new tag
    - tags
